replicaCount: 1

image:
  repository: anujtomar1/node-express-hello-world
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 3000

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths: ["/"]

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}
